global:
  scrape_interval: 1m

rule_files:
  - prometheus_rules.yml

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
    - targets: ["node-exporter:9100"]
  
alerting:
  alertmanagers:
    - static_configs: 
      - targets: ['localhost:9093','alertmanager:9093']

# remote_write:
#   - url: "<Your Prometheus remote_write endpoint>"
#     basic_auth:
#       username: "<Your Grafana Username>"
#       password: "<Your Grafana API key>"